CREATE DATABASE Impeooo;

USE Impeooo;

CREATE TABLE Word(
	Id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    Text VARCHAR(200) NOT NULL,
    CreatedAt DATETIME,
    UpdatedAt DATETIME
);

CREATE TABLE User(
	Id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    Username VARCHAR(100) NOT NULL,
    Email VARCHAR(180) NOT NULL,
    Password VARCHAR(50) NOT NULL,
    CreatedAt DATETIME,
    UpdatedAt DATETIME
);